### ISSUE TITLE
想和您一起开发象棋爱，不知道意见如何？

### ISSUE THREAD

**Issue by Ways49** [yuanluo2/Small-Chinese_Chess_Cpp#1]
我自己一个人写ai力不从心，之前写过但是工程量太大了，就问问。

**Comment by Sky-And-Ground** [comment]
可以的，这个项目的初衷其实就是写一个有AI且跑在命令行下的中国象棋，后来有了SFML这个游戏引擎以后，我就有点心思，想给它弄成带界面的了

**Comment by Ways49** [comment]
那麻烦加个联系方式么？只是讨论象棋ai

**Comment by Sky-And-Ground** [comment]
若不然你给个qq或者wechat

**Comment by Ways49** [comment]
1436980420 qq
